namespace GameStore.Api.Dtos;

public record class CreateGameDto(
    string Name, 
    string Genre, 
    decimal Price, 
    DateOnly ReleaseDate);
// This DTO is used for creating a new game. It does not include the Id property, as it will be generated by the database.
