using System.ComponentModel.DataAnnotations;

namespace GameStore.Api.Dtos;

public record class CreateGameDto(
    [Required][StringLength(50)] string Name,
    int GenreId, // Ensure GenreId is marked as required
    [Range(1, 100)] decimal Price,
    DateOnly ReleaseDate);
// This DTO is used for creating a new game. It does not include the Id property, as it will be generated by the database.